config/routes.rb
  post '/dataUpload/import_images' => 'data_upload#import_images'
  post '/dataUpload/import_stock' => 'data_upload#import_stock'
  get '/dataUpload/uploadBanner' => 'data_upload#uploadBanner'
  post '/dataUpload/upload_banner_image' => 'data_upload#upload_banner_image'
  post '/dataUpload/delete_banner_image' => 'data_upload#delete_banner_image'
  post '/dataUpload/assign_image' => 'data_upload#assign_image'
  post '/dataUpload/import_comparable_attributes' => 'data_upload#import_comparable_attributes', as: 'import_comparable_attributes'
  post '/dataUpload/import_related_products' => 'data_upload#import_related_products'
  post '/dataUpload/import_offer_prices' => 'data_upload#import_offer_prices'
  post '/dataUpload/import_products_metadata' => 'data_upload#import_products_metadata'
  post '/dataUpload/import_categories_metadata' => 'data_upload#import_categories_metadata'
  get'/dataUpload/synchronize_products_with_miele_core' => 'data_upload#synchronize_products_with_miele_core'
  get'/dataUpload/synchronize_stock_and_price_products_with_miele_core' => 'data_upload#synchronize_stock_and_price_products_with_miele_core'

  post '/dataUpload/import_tech_documents' => 'data_upload#import_tech_documents'
  get '/dataUpload/download_categories_template' => 'data_upload#download_categories_template', :as => "categories_template_path"
  get '/dataUpload/download_products_template' => 'data_upload#download_products_template', :as => "products_template_path"
  get '/dataUpload/download_stock_template' => 'data_upload#download_stock_template', :as => "stock_template_path"
  get '/dataUpload/download_related_products_template' => 'data_upload#download_related_products_template', :as => "related_products_template_path"
  get '/dataUpload/download_offer_prices_template' => 'data_upload#download_offer_prices_template', :as => "offer_prices_template_path"
  get '/dataUpload/download_products_metadata_template' => 'data_upload#download_products_metadata_template', :as => "products_metadata_template_path"
  get '/dataUpload/download_categories_metadata_template' => 'data_upload#download_categories_metadata_template', :as => "categories_metadata_template_path"

  get '/download/stock' => 'data_upload#download_stock', as: 'download_stock'
  get '/download/products' => 'data_upload#download_products', as: 'download_products'
  get '/download/related_products' => 'data_upload#download_related_products', as: 'download_related_products'
  get '/download/offer_prices' => 'data_upload#download_offer_prices', as: 'download_offer_prices'
  get '/download/products_metadata' => 'data_upload#download_products_metadata', as: 'download_products_metadata'
  get '/download/categories_metadata' => 'data_upload#download_categories_metadata', as: 'download_categories_metadata'

  
  get 'comunas/comuna_by_region' => 'comunas#comuna_by_region'

  post '/lineItem/destroy_item' => 'line_item#destroy_item', :as => "line_item_destroy_item_path"

  get '/tag_manager' => 'tag_manager#index'
  post '/tag_manager/update' => 'tag_manager#update'

  post '/webpay/webpay_final_url', to: 'webpay#webpay_final_url', as: :webpay_result
  post '/webpay/return_url', to: 'webpay#return_url', as: :webpay_return
  post '/webpay/nullify_order', to: 'webpay#nullify_order', as: :nullify_order
  post '/user/update', to: 'local_user#update', as: :update_user
  
  resources :promotional_banners, except: [:destroy, :show]
  get 'promotional_banners/categories', to: 'promotional_banners#categories', as: 'categories_banners'
  get 'promotional_banners/categories/:taxon_id/add', to: 'promotional_banners#categories_add_banner', as: 'add_banner_to_category'

  get 'quotations/new/:product_id', to: 'quotations#new', as: 'quotation_new'
  post 'quotations', to: 'quotations#create', as: 'quotations'
  get 'quotations/success', to: 'quotations#success', as: 'success_quotation_request'

  resources :static_pages
  resources :miele_configs, only: [:index, :edit, :update]

  
  get 'admin/virtual_support', to: 'virtual_support#edit', as: :virtual_support
  patch 'admin/virtual_support', to: 'virtual_support#update'
  get 'agendamiento-cita-virtual', to: 'virtual_support#new', as: :new_virtual_support
  
  Spree::Core::Engine.routes.draw do

    get 'store_notices_controller/index'
    get 'store_notices_controller/new'

    get 'products/:id/list_prices', to: 'products#list_prices', as: 'list_product_prices'

    get 'oportunities', to: 'products#oportunities', as: 'oportunities'

    resources :provinces
    namespace :admin, path: Spree.admin_path do

      resources :reports, only: [:index] do
        collection do
          get :dashboard
          get :sales_total
          get :promotions
          get :promotions_pdf
          get :sales_product_total
          get :sales_product_total_pdf
          post :sales_product_total
          get :viewed_product_total
          get :viewed_product_total_pdf
          get :loyal_customers
          get :loyal_customers_pdf
          get :customers_over_time
          get :customers_over_time_pdf
          get :visits_over_time
          get :visits_over_time_pdf
          get :visits_by_page
          get :visits_by_page_pdf
          post :sales_total
          get :searches
        end
      end
      resources :products, only: [:index] do
        collection do
          post :create_tag
          post :delete_documents
          get :documents
          get :change_state_of_product
        end
      end
      get 'configurations', :to => 'base#configurations', :as => :configurations
      get '/download_users', :to => 'users#download_users', :as => :download_users
      get '/download_new_users', :to => 'users#download_new_users', :as => :download_new_users
      get '/download_orders', :to => 'orders#download_orders', :as => :download_orders
      get '/download_orders_summary', :to => 'orders#download_orders_summary', :as => :download_orders_summary
      delete '/delete_comment/:id', :to => 'comments#destroy', :as => :delete_comment
      get '/new_users', :to => 'users#new_users', :as => :new_users

      get 'orders/:id/ready' => 'orders#ready', :as => :order_ready
      get 'orders/:id/ship' => 'orders#ship', :as => :order_ship
      get 'orders/:id/deliver' => 'orders#deliver', :as => :order_deliver
      get 'orders/update_massive_orders' => 'orders#update_massive_orders', :as => :order_update_massive_orders
      get 'orders/:id/resend_order_to_b2b' => 'orders#resend_order_to_b2b', :as => :resend_order_to_b2b

      get 'products/:id/comparable_attributes', to: 'products#comparable_attributes', as: :product_comparable_attributes
      get 'products/:id/comparable_attributes/:attribute_id/edit', to: 'products#edit_comparable_attribute', as: :edit_product_comparable_attribute
      patch 'products/:id/comparable_attributes/:attribute_id/update', to: 'products#update_comparable_attribute', as: :update_product_comparable_attribute

      get 'products/:id/specific_attributes', to: 'products#specific_attributes', as: :product_specific_attributes
      get 'products/:id/specific_attributes/:attribute_id/:attribute_name/edit/:is_boolean', to: 'products#edit_specific_attribute', as: :edit_product_specific_attribute
      patch 'products/:id/specific_attributes/:attribute_id/update', to: 'products#update_specific_attribute', as: :update_product_specific_attribute

      delete 'orders/:id', to: 'orders#destroy', as: :soft_delete_order

      get '/download_searches' => 'reports#download_searches', as: :download_searches
      get '/download_visits_by_page' => 'reports#download_visits_by_page', as: :download_visits_by_page
      get '/download_visits_over_time' => 'reports#download_visits_over_time', as: :download_visits_over_time
      get '/download_customers_over_time' => 'reports#download_customers_over_time', as: :download_customers_over_time
      get '/download_loyal_customers' => 'reports#download_loyal_customers', as: :download_loyal_customers
      get '/download_viewed_product_total' => 'reports#download_viewed_product_total', as: :download_viewed_product_total
      get '/download_sales_product_total' => 'reports#download_sales_product_total', as: :download_sales_product_total
      get '/download_promotions' => 'reports#download_promotions', as: :download_promotions
      get '/download_sales_total' => 'reports#download_sales_total', as: :download_sales_total
    end
    post 'products/fetch_stock'
    get '/products/most_selled' => 'products#most_selled'
    get 'products/recents' => 'products#recents', :as => :recents 
    get 'webpay/success', :to => 'checkout#webpay_success', :as => :webpay_success
    get 'webpay/error', :to => 'checkout#webpay_error', :as => :webpay_error
    get 'webpay/nullify', :to => 'checkout#webpay_nullify', :as => :webpay_nullify
    post 'store/newsletter' => 'store#newsletter' , :as => 'newsletter_create'
    post 'repeat/repeat_last_complete_order', :to => 'orders#repeat_last_complete_order' , :as => :repeat_last_complete_order
    post 'repeat/repeat_order', :to => 'orders#repeat_order' , :as => :repeat_order
    post 'orders/populate_ajax', :to => 'orders#populate_ajax' , :as => :populate_ajax
    post 'orders/update_ajax', :to => 'orders#update_ajax' , :as => :update_ajax
    post 'products/properties', :to => 'products#properties' , :as => :properties
    post 'orders/custom_apply_coupon', :to => 'orders#custom_apply_coupon' , :as => :custom_apply_coupon
    get 'orders/show_apply_coupon_form', to: 'orders#show_apply_coupon_form', as: :show_apply_coupon_form
    post 'orders/update_step', :to => 'orders#update_step' , :as => :update_step
    patch 'orders/update_item/quantity', to: 'orders#update_item_quantity'
    patch 'orders/update_item/installation', to: 'orders#update_item_installation'
    
    post 'orders/update/shipping_address/ajax', to: 'orders#update_shipping_address_ajax'
    post 'orders/remove_item', to: 'orders#remove_item'

app/models/spree/promotion/actions/miele_adjustment.rb
module Spree
  class Promotion
    module Actions
      class MieleAdjustment < PromotionAction
        include Spree::CalculatedAdjustments
        include Spree::AdjustmentSource

        before_validation -> { self.calculator ||= Calculator::MieleFlatPercentItemTotal.new }

        def perform(options = {})
          order = options[:order]
          create_unique_adjustment(order, order)
        end

        def compute_amount(order)
          [(order.item_total + order.ship_total), compute(order)].min * -1
        end
      end
    end
  end
end

app/models/spree/promotion/rules/miele_policy.rb
module Spree
  class Promotion
    module Rules
      class MielePolicy < PromotionRule
        preference :amount_min, :decimal, default: 100.00
        preference :operator_min, :string, default: '>'
        preference :amount_max, :decimal, default: 1000.00
        preference :operator_max, :string, default: '<'


        OPERATORS_MIN = ['gt', 'gte']
        OPERATORS_MAX = ['lt','lte']

        def applicable?(promotable)
          promotable.is_a?(Spree::Order)
        end

        def eligible?(order, options = {})
          item_total = order.total_without_products_in_offer

          lower_limit_condition = item_total.send(preferred_operator_min == 'gte' ? :>= : :>, BigDecimal.new(preferred_amount_min.to_s))
          upper_limit_condition = item_total.send(preferred_operator_max == 'lte' ? :<= : :<, BigDecimal.new(preferred_amount_max.to_s))

          eligibility_errors.add(:base, ineligible_message_max) unless upper_limit_condition
          eligibility_errors.add(:base, ineligible_message_min) unless lower_limit_condition
          # eligibility_errors.add(:base, 'La suma de descuentos de precios ofertas es mayor que la de la promoción') unless promotion_better_than_offer_prices?(order)

          eligibility_errors.empty?
        end

        private
        def formatted_amount_min
          Spree::Money.new(preferred_amount_min).to_s
        end

        def formatted_amount_max
          Spree::Money.new(preferred_amount_max).to_s
        end


        def ineligible_message_max
          if preferred_operator_max == 'gte'
            eligibility_error_message(:item_total_more_than_or_equal, amount: formatted_amount_max)
          else
            eligibility_error_message(:item_total_more_than, amount: formatted_amount_max)
          end
        end

        def ineligible_message_min
          if preferred_operator_min == 'gte'
            eligibility_error_message(:item_total_less_than, amount: formatted_amount_min)
          else
            eligibility_error_message(:item_total_less_than_or_equal, amount: formatted_amount_min)
          end
        end

        def promotion_better_than_offer_prices?(order)
          return (promotion_discount(without_product_offers(order)).abs > offer_prices_discount(order).abs)
        end

        def offer_prices_discount(order)
          return order.total_without_product_offers - order.amount
        end

        def promotion_discount(order)
          return promotion.actions.map{|action| action.calculator.compute(order)}.sum
        end

        def without_product_offers(order)
          new_order = Spree::Order.new
          new_order.item_total = order.item_total
          new_order.ship_total = order.ship_total
          new_line_items = order.line_items.map do |line_item| 
            new_line_item = line_item.dup
            new_line_item.price = line_item.variant.price
            new_line_item
          end
          new_order.line_items << new_line_items
          return new_order
        end
      end
    end
  end
end

app/models/spree/promotion/rules/taxon.rb
module Spree
  class Promotion
    module Rules
      class Taxon < PromotionRule
        has_many :promotion_rule_taxons, class_name: 'Spree::PromotionRuleTaxon', foreign_key: 'promotion_rule_id'
        has_many :taxons, through: :promotion_rule_taxons, class_name: 'Spree::Taxon'

        MATCH_POLICIES = %w(any all two_products three_products)
        preference :match_policy, default: MATCH_POLICIES.first

        def applicable?(promotable)
          promotable.is_a?(Spree::Order)
        end

        def eligible?(order, options = {})
          case preferred_match_policy
            when 'all'
              unless (taxons.to_a - taxons_in_order_including_parents(order)).empty?
                eligibility_errors.add(:base, eligibility_error_message(:missing_taxon))
              end
            when 'any'
              order_taxons = taxons_in_order_including_parents(order)
              unless taxons.any?{ |taxon| order_taxons.include? taxon }
                eligibility_errors.add(:base, eligibility_error_message(:no_matching_taxons))
              end
            when 'two_products' 
              unless products_quantity_inside_taxon(order) >= 2
                eligibility_errors.add(:base, eligibility_error_message(:insufficient_products_quantity_2))
              end
            when 'three_products' 
              unless products_quantity_inside_taxon(order) >= 3
                eligibility_errors.add(:base, eligibility_error_message(:insufficient_products_quantity_3))
              end
          end
          eligibility_errors.empty?
        end

        def actionable?(line_item)
          (!line_item.variant.product.offer_price_available? and 
           taxon_product_ids.include? line_item.variant.product_id)
        end

        def taxon_ids_string
          taxons.pluck(:id).join(',')
        end

        def taxon_ids_string=(s)
          ids = s.to_s.split(',').map(&:strip)
          self.taxons = Spree::Taxon.find(ids)
        end

        def product_ids_in_promotion(order)
          product_ids_in_order = order.line_items.map{|l| l.variant.product_id}
          return product_ids_in_order - taxon_product_ids
        end

        def products
          Spree::Product.joins(:taxons).where(spree_taxons: {id: taxons.pluck(:id)})
        end

        private

        def taxon_product_ids
          Spree::Product.joins(:taxons).where(spree_taxons: {id: taxons.pluck(:id)}).pluck(:id).uniq
        end

        def products_quantity_inside_taxon(order)
          quantity = 0
          order.line_items.each do |line_item|
            if (!line_item.variant.product.offer_price_available? and taxon_product_ids.include?(line_item.variant.product_id))
              quantity += line_item.quantity
            end
          end
          return quantity
        end

        # All taxons in an order
        def order_taxons(order)
          Spree::Taxon.joins(products: {variants_including_master: :line_items})
                      .where(spree_line_items: {order_id: order.id}).uniq
        end

        # ids of taxons rules and taxons rules children
        def taxons_including_children_ids
          taxons.inject([]){ |ids,taxon| ids += taxon.self_and_descendants.ids }
        end

        # taxons order vs taxons rules and taxons rules children
        def order_taxons_in_taxons_and_children(order)
          order_taxons(order).where(id: taxons_including_children_ids)
        end

        def taxons_in_order_including_parents(order)
          order_taxons_in_taxons_and_children(order).inject([]){ |taxons, taxon| taxons << taxon.self_and_ancestors }.flatten.uniq
        end
      end
    end
  end
end

app/views/spree/admin/promotions/_form.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @promotion } %>

<div class="row" id="general_fields" >
  <div class="col-md-3">
    <%= f.field_container :name, class: ['form-group'] do %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.error_message_on :name %>
    <% end %>

    <%= f.field_container :code, class: ['form-group'] do %>
      <%= f.label :code %>
      <%= f.text_field :code, class: 'form-control' %>
    <% end %>

    <%= f.field_container :path, class: ['form-group hidden'] do %>
      <%= f.label :path %>
      <%= f.text_field :path, class: 'form-control' %>
    <% end %>

    <%= f.field_container :advertise, class: ['checkbox hidden'] do %>
      <%= f.label :advertise do %>
        <%= f.check_box :advertise %>
        <%= Spree.t(:advertise) %>
      <% end %>
    <% end %>
  </div>

  <div class="col-md-6">
    <%= f.field_container :description, class: ['form-group'] do %>
      <%= f.label :description %>
      <%= f.text_area :description, rows: 7, class: 'form-control' %>
    <% end %>

    <%= f.field_container :category, class: ['form-group'] do %>
      <%= f.label :promotion_category %>
      <%= f.collection_select(:promotion_category_id, @promotion_categories, :id, :name, { include_blank: Spree.t('match_choices.none') }, { class: 'select2' }) %>
    <% end %>
  </div>

  <div id="expiry_fields" class="col-md-3">
    <%= f.field_container :usage_limit do %>
      <%= f.label :usage_limit %>
      <%= f.number_field :usage_limit, min: 0, class: 'form-control' %>
      <p class="help-block">
        <%= Spree.t(:current_promotion_usage, count: @promotion.credits_count) %>
      </p>
    <% end %>

    <div id="starts_at_field" class="form-group">
      <%= f.label :starts_at %>
      <%= f.text_field :starts_at, value: datepicker_field_value(@promotion.starts_at), class: 'datepicker datepicker-from form-control' %>
    </div>

    <div id="expires_at_field" class="form-group">
      <%= f.label :expires_at %>
      <%= f.text_field :expires_at, value: datepicker_field_value(@promotion.expires_at), class: 'datepicker datepicker-to form-control' %>
    </div>
  </div>
</div>

app/views/spree/admin/promotions/edit.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:promotions), admin_promotions_url %> /
  <%= @promotion.name %>
<% end %>
<% content_for :page_actions do %>
  <%= render partial: 'spree/admin/shared/help', locals: {title_help: t(:admin_help_edit_promotion_title), body_help: t(:admin_help_edit_promotion_body)} %>
<% end %>
<%= form_for @promotion, url: object_url, method: :put do |f| %>
  <div class="row">
    <div class="col-md-12">
      <%= render partial: 'form', locals: { f: f } %>
      <%= render partial: 'spree/admin/shared/edit_resource_links' %>
    </div>
  </div>

<% end %>
<div class="pull-right">	
  <%= render partial: 'spree/admin/shared/help', locals: {title_help: t(:admin_help_edit_promotion_rules_title), body_help: t(:admin_help_edit_promotion_rules_body), option_id: "rules"} %>
</div>
<br><br><br>
<div id="promotion-filters" class="row">
  <div id="rules_container" class="col-md-6">
    <div class="panel panel-default">
      <%= render partial: 'rules' %>
    </div>
  </div>

  <div id="actions_container" class="col-md-6">
    <div class="panel panel-default">
      <%= render partial: 'actions' %>
    </div>
  </div>
</div>
<%= render partial: "spree/admin/variants/autocomplete", formats: [:js] %>

app/views/spree/admin/promotions/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Promotion) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_promotion), new_object_url, class: "btn-success", icon: 'add' %>
  <%= render partial: 'spree/admin/shared/help', locals: {title_help: t(:admin_help_promotion_title), body_help: t(:admin_help_promotion_body)} %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_promotions_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= label_tag :q_name_cont, Spree.t(:name) %>
            <%= f.text_field :name_cont, tabindex: 1, class: "form-control js-quick-search-target" %>
          </div>

          <div class="form-group">
            <%= label_tag :q_code_cont, Spree.t(:code) %>
            <%= f.text_field :code_cont, tabindex: 1, class: "form-control" %>
          </div>
        </div>

        <div class="col-md-6">
          <div class="form-group">
            <%= label_tag :q_path_cont, Spree.t(:path) %>
            <%= f.text_field :path_cont, tabindex: 1, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= label_tag :q_promotion_category_id_eq, Spree.t(:promotion_category) %>
            <%= f.collection_select(:promotion_category_id_eq, @promotion_categories, :id, :name, { include_blank: Spree.t('match_choices.all') }, { class: 'select2' }) %>
          </div>
        </div>
      </div>

      <div data-hook="admin_promotions_index_search_buttons" class="form-actions">
        <%= button Spree.t(:filter_results), 'search' %>
      </div>
    <% end %>
  </div>
<% end %>

<%= paginate @promotions %>

<% if @promotions.any? %>
  <table class="table">
    <thead>
      <tr>
        <th><%= Spree.t(:name) %></th>
        <th><%= Spree.t(:code) %></th>
        <th><%= Spree.t(:description) %></th>
        <th><%= Spree.t(:usage_limit) %></th>
        <th><%= Spree.t(:promotion_uses) %></th>
        <th><%= Spree.t(:expiration) %></th>
        <th data-hook="admin_promotions_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @promotions.each do |promotion| %>
        <tr id="<%= spree_dom_id promotion %>">
          <td><%= link_to promotion.name, edit_admin_promotion_path(promotion) %></td>
          <td><%= promotion.code %></td>
          <td><%= promotion.description %></td>
          <td><%= promotion.usage_limit.nil? ? "∞" : promotion.usage_limit  %></td>
          <td><%= Spree.t(:current_promotion_usage, count: promotion.credits_count) %></td>
          <td><%= promotion.expires_at.to_date.to_s(:short_date) if promotion.expires_at %></td>
          <td class="actions actions-2" data-hook="admin_promotions_index_row_actions">
            <%= link_to_edit promotion, no_text: true %>
            <%= link_to_delete promotion, no_text: true %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Promotion)) %>,
    <%= link_to Spree.t(:add_one), new_object_url %>!
  </div>
<% end %>