config/routes.rb
Rails.application.routes.draw do

  resources :store_notices, only: [:index, :new, :create, :destroy]
  resources :provinces
  resources :newsletter_subscribers
  get '/download_subscriptors', :to => 'newsletter_subscribers#download_all'
  get '/newsletter/popup', to: 'spree/home#newsletter_popup', as: :show_popup

  mount Spree::Core::Engine, at: '/'

  get 'static_pages/new', to: 'static_pages#new', as: 'new_static_page'
  get 'static_pages/:id/destroy', to: 'static_pages#destroy', as: 'delete_static_page'
  get 'static_pages/:slug', to: 'static_pages#show', as: 'about_store'

  get '/dataUpload/uploadData' => 'data_upload#upload_data', as: 'upload_data'
  post '/dataUpload/import_categories' => 'data_upload#import_categories'
  post '/dataUpload/import_products' => 'data_upload#import_products'
  post '/dataUpload/import_images' => 'data_upload#import_images'
  post '/dataUpload/import_stock' => 'data_upload#import_stock'
  get '/dataUpload/uploadBanner' => 'data_upload#uploadBanner'
  post '/dataUpload/upload_banner_image' => 'data_upload#upload_banner_image'
  post '/dataUpload/delete_banner_image' => 'data_upload#delete_banner_image'
  post '/dataUpload/assign_image' => 'data_upload#assign_image'
  post '/dataUpload/import_comparable_attributes' => 'data_upload#import_comparable_attributes', as: 'import_comparable_attributes'
  post '/dataUpload/import_related_products' => 'data_upload#import_related_products'
  post '/dataUpload/import_offer_prices' => 'data_upload#import_offer_prices'
  post '/dataUpload/import_products_metadata' => 'data_upload#import_products_metadata'
  post '/dataUpload/import_categories_metadata' => 'data_upload#import_categories_metadata'
  get'/dataUpload/synchronize_products_with_miele_core' => 'data_upload#synchronize_products_with_miele_core'
  get'/dataUpload/synchronize_stock_and_price_products_with_miele_core' => 'data_upload#synchronize_stock_and_price_products_with_miele_core'

  post '/dataUpload/import_tech_documents' => 'data_upload#import_tech_documents'
  get '/dataUpload/download_categories_template' => 'data_upload#download_categories_template', :as => "categories_template_path"
  get '/dataUpload/download_products_template' => 'data_upload#download_products_template', :as => "products_template_path"
  get '/dataUpload/download_stock_template' => 'data_upload#download_stock_template', :as => "stock_template_path"
  get '/dataUpload/download_related_products_template' => 'data_upload#download_related_products_template', :as => "related_products_template_path"
  get '/dataUpload/download_offer_prices_template' => 'data_upload#download_offer_prices_template', :as => "offer_prices_template_path"
  get '/dataUpload/download_products_metadata_template' => 'data_upload#download_products_metadata_template', :as => "products_metadata_template_path"
  get '/dataUpload/download_categories_metadata_template' => 'data_upload#download_categories_metadata_template', :as => "categories_metadata_template_path"

  get '/download/stock' => 'data_upload#download_stock', as: 'download_stock'
  get '/download/products' => 'data_upload#download_products', as: 'download_products'
  get '/download/related_products' => 'data_upload#download_related_products', as: 'download_related_products'
  get '/download/offer_prices' => 'data_upload#download_offer_prices', as: 'download_offer_prices'
  get '/download/products_metadata' => 'data_upload#download_products_metadata', as: 'download_products_metadata'
  get '/download/categories_metadata' => 'data_upload#download_categories_metadata', as: 'download_categories_metadata'

  
  get 'comunas/comuna_by_region' => 'comunas#comuna_by_region'

  post '/lineItem/destroy_item' => 'line_item#destroy_item', :as => "line_item_destroy_item_path"

  get '/tag_manager' => 'tag_manager#index'
  post '/tag_manager/update' => 'tag_manager#update'

  post '/webpay/webpay_final_url', to: 'webpay#webpay_final_url', as: :webpay_result
  post '/webpay/return_url', to: 'webpay#return_url', as: :webpay_return
  post '/webpay/nullify_order', to: 'webpay#nullify_order', as: :nullify_order
  post '/user/update', to: 'local_user#update', as: :update_user
  
  resources :promotional_banners, except: [:destroy, :show]
  get 'promotional_banners/categories', to: 'promotional_banners#categories', as: 'categories_banners'
  get 'promotional_banners/categories/:taxon_id/add', to: 'promotional_banners#categories_add_banner', as: 'add_banner_to_category'

  get 'quotations/new/:product_id', to: 'quotations#new', as: 'quotation_new'
  post 'quotations', to: 'quotations#create', as: 'quotations'
  get 'quotations/success', to: 'quotations#success', as: 'success_quotation_request'

  resources :static_pages
  resources :miele_configs, only: [:index, :edit, :update]

  
  get 'admin/virtual_support', to: 'virtual_support#edit', as: :virtual_support
  patch 'admin/virtual_support', to: 'virtual_support#update'
  get 'agendamiento-cita-virtual', to: 'virtual_support#new', as: :new_virtual_support
  
  Spree::Core::Engine.routes.draw do

    get 'store_notices_controller/index'
    get 'store_notices_controller/new'

    get 'products/:id/list_prices', to: 'products#list_prices', as: 'list_product_prices'

    get 'oportunities', to: 'products#oportunities', as: 'oportunities'

    resources :provinces
    namespace :admin, path: Spree.admin_path do

      resources :reports, only: [:index] do
        collection do
          get :dashboard
          get :sales_total
          get :promotions
          get :promotions_pdf
          get :sales_product_total
          get :sales_product_total_pdf
          post :sales_product_total
          get :viewed_product_total
          get :viewed_product_total_pdf
          get :loyal_customers
          get :loyal_customers_pdf
          get :customers_over_time
          get :customers_over_time_pdf
          get :visits_over_time
          get :visits_over_time_pdf
          get :visits_by_page
          get :visits_by_page_pdf
          post :sales_total
          get :searches
        end
      end
      resources :products, only: [:index] do
        collection do
          post :create_tag
          post :delete_documents
          get :documents
          get :change_state_of_product
        end
      end
      get 'configurations', :to => 'base#configurations', :as => :configurations
      get '/download_users', :to => 'users#download_users', :as => :download_users
      get '/download_new_users', :to => 'users#download_new_users', :as => :download_new_users
      get '/download_orders', :to => 'orders#download_orders', :as => :download_orders
      get '/download_orders_summary', :to => 'orders#download_orders_summary', :as => :download_orders_summary
      delete '/delete_comment/:id', :to => 'comments#destroy', :as => :delete_comment
      get '/new_users', :to => 'users#new_users', :as => :new_users

      get 'orders/:id/ready' => 'orders#ready', :as => :order_ready
      get 'orders/:id/ship' => 'orders#ship', :as => :order_ship
      get 'orders/:id/deliver' => 'orders#deliver', :as => :order_deliver
      get 'orders/update_massive_orders' => 'orders#update_massive_orders', :as => :order_update_massive_orders
      get 'orders/:id/resend_order_to_b2b' => 'orders#resend_order_to_b2b', :as => :resend_order_to_b2b

      get 'products/:id/comparable_attributes', to: 'products#comparable_attributes', as: :product_comparable_attributes
      get 'products/:id/comparable_attributes/:attribute_id/edit', to: 'products#edit_comparable_attribute', as: :edit_product_comparable_attribute
      patch 'products/:id/comparable_attributes/:attribute_id/update', to: 'products#update_comparable_attribute', as: :update_product_comparable_attribute

      get 'products/:id/specific_attributes', to: 'products#specific_attributes', as: :product_specific_attributes
      get 'products/:id/specific_attributes/:attribute_id/:attribute_name/edit/:is_boolean', to: 'products#edit_specific_attribute', as: :edit_product_specific_attribute
      patch 'products/:id/specific_attributes/:attribute_id/update', to: 'products#update_specific_attribute', as: :update_product_specific_attribute

      delete 'orders/:id', to: 'orders#destroy', as: :soft_delete_order

      get '/download_searches' => 'reports#download_searches', as: :download_searches
      get '/download_visits_by_page' => 'reports#download_visits_by_page', as: :download_visits_by_page
      get '/download_visits_over_time' => 'reports#download_visits_over_time', as: :download_visits_over_time
      get '/download_customers_over_time' => 'reports#download_customers_over_time', as: :download_customers_over_time
      get '/download_loyal_customers' => 'reports#download_loyal_customers', as: :download_loyal_customers
      get '/download_viewed_product_total' => 'reports#download_viewed_product_total', as: :download_viewed_product_total
      get '/download_sales_product_total' => 'reports#download_sales_product_total', as: :download_sales_product_total
      get '/download_promotions' => 'reports#download_promotions', as: :download_promotions
      get '/download_sales_total' => 'reports#download_sales_total', as: :download_sales_total
    end
    post 'products/fetch_stock'
    get '/products/most_selled' => 'products#most_selled'
    get 'products/recents' => 'products#recents', :as => :recents 
    get 'webpay/success', :to => 'checkout#webpay_success', :as => :webpay_success
    get 'webpay/error', :to => 'checkout#webpay_error', :as => :webpay_error
    get 'webpay/nullify', :to => 'checkout#webpay_nullify', :as => :webpay_nullify
    post 'store/newsletter' => 'store#newsletter' , :as => 'newsletter_create'
    post 'repeat/repeat_last_complete_order', :to => 'orders#repeat_last_complete_order' , :as => :repeat_last_complete_order
    post 'repeat/repeat_order', :to => 'orders#repeat_order' , :as => :repeat_order

app/models/promotional_banner.rb
class PromotionalBanner < ActiveRecord::Base
  belongs_to :taxon, class_name: 'Spree::Taxon', foreign_key: 'spree_taxon_id'

  has_attached_file :image, styles: {
    large: "1920x1200",
    medium: "300x300", 
    thumb: "100x100" 
  }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  has_attached_file :mobile_image, styles: {
    normal: "500x500", 
    thumb: "100x100" 
  }
  validates_attachment_content_type :mobile_image, content_type: /\Aimage\/.*\Z/

  enum location: {
    home_1: 0,
    home_2: 1,
    home_3: 2,
    home_4: 3,
    sidebar_category: 4,
    category_bar: 5,
    taxon: 6
  }

  def location_help_url
      if self.location == "category_bar" 
        return ActionController::Base.helpers.asset_path('banners/category_bar.jpg')
      elsif self.location == "home_1" 
        return ActionController::Base.helpers.asset_path('banners/home_1.jpg')
      elsif self.location == "home_2" 
        return ActionController::Base.helpers.asset_path('banners/home_2.jpg')
      elsif self.location == "home_3" 
        return ActionController::Base.helpers.asset_path('banners/home_3.jpg')
      elsif self.location == "home_4" 
        return ActionController::Base.helpers.asset_path('banners/home_4.jpg')
      elsif self.location == "sidebar_category" 
        return ActionController::Base.helpers.asset_path('banners/sidebar_category.jpg')
      else
        return "#"
      end
  end

  def self.location_options
    return [
      ['Home 1', 0],
      ['Home 2', 1],
      ['Home 3', 2],
      ['Home 4', 3],
      ['Sidebar en específico', 4],
      ['Barra de categorías', 5]
    ]
  end
end

app/controllers/promotional_banners_controller.rb
class PromotionalBannersController < Spree::BaseController
  include Spree::Core::Engine.routes.url_helpers
  include Spree::Core::Engine.helpers
  include Spree::Core::ControllerHelpers
  include Spree::Core::ControllerHelpers::Order
  layout '/spree/layouts/admin'

  before_action :authenticate_spree_user!
  before_action :set_promotional_baner, only: [:edit, :update]
  
  def index
    @promotional_banners = PromotionalBanner.where.not(location: 6)
  end

  def new
    @promotional_banner = PromotionalBanner.new
  end

  def create
    @promotional_banner = PromotionalBanner.new(promotional_banner_params)
    respond_to do |format|
      if @promotional_banner.save
        if @promotional_banner.taxon
          format.html{ redirect_to main_app.categories_banners_path, notice: 'Banner creado con éxito'}
        else
          format.html{ redirect_to main_app.promotional_banners_path, notice: 'Banner creado con éxito'}
        end
      else
        raise @promotional_banner.errors.inspect
        format.html{ redirect_to :back, alert: 'Ha ocurrido un error. Intente nuevamente'}
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @promotional_banner.update(promotional_banner_params)
        format.html{ redirect_to main_app.promotional_banners_path}
      else
        format.html{ redirect_to :back, alert: 'Ha ocurrido un error. Intente nuevamente'}
      end
    end
  end

  def categories
    @taxons = Spree::Taxon.all.includes(:banner)
    @taxonomies = Spree::Taxonomy.includes(root: :children)
  end

  def categories_add_banner
    @taxon = Spree::Taxon.find_by(id: params[:taxon_id])
    if @taxon and @taxon.banner
      @taxon.banner.destroy
    end
    @promotional_banner = PromotionalBanner.new
  end

  private 

    def promotional_banner_params
      data = params.require(:promotional_banner)
                 .permit(:title, :link, :alt, :location, 
                         :image, :active, :mobile_image)

      taxon = Spree::Taxon.find_by(id: params[:promotional_banner][:taxon_id])
      return data.merge({taxon: taxon})
    end

    def set_promotional_baner
      @promotional_banner = PromotionalBanner.find(params[:id])
    end
end

app/helpers/promotional_banners_helper.rb
module PromotionalBannersHelper
  def category_banner_row(taxon)
    if taxon.banner
      link = link_to 'Editar banner', main_app.add_banner_to_category_path(taxon.id), class: 'btn btn-success btn-sm add-banner'
    else
      link = link_to 'Agregar banner', main_app.add_banner_to_category_path(taxon.id), class: 'btn btn-primary btn-sm add-banner'
    end
    return "<tr>
      <td class='category-depth-#{taxon.depth}'>#{taxon.name}</td>
      <td>
        #{image_tag taxon.banner.image.url(:thumb), class: 'category-banner' if taxon.banner}
      </td>
      <td>
        #{link}
      </td>
    </tr>".html_safe
  end
end

app/views/promotional_banners/_form.html.erb
<%= form_for @promotional_banner, url: url_path, method: method_type, multipart: true do |f| %>
  
  <div class="form-group">
    <%= f.label :title, 'Título' %>
    <%= f.text_field :title, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :link, 'URL Asociada' %>
    <%= f.url_field :link, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :image, 'Imagen' %>
    <%= f.file_field :image %>
  </div>

  <div class="form-group">
    <%= f.label :mobile_image, 'Imagen para móviles' %>
    <%= f.file_field :mobile_image %>
  </div>

  <div class="form-group">
    <%= f.label :alt, 'Texto alternativo' %>
    <%= f.text_field :alt, class: 'form-control' %>
  </div>

  <% if params[:action] == 'new' %>
    <div class="form-group">
      <%= f.label :location, 'Ubicación' %>
      <%= f.select :location, options_for_select(PromotionalBanner.locations.keys, @promotional_banner.location), {}, {class: 'select2'} %>
    </div>
   
  <% end %>
   <div class="form-group">
      <%= f.label :active, 'Estado' %>
      <%= f.select :active, options_for_select(['Activo','Inactivo']) %>
    </div>

  <div class="form-group">
    <%= f.submit 'Guardar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/promotional_banners/categories.html.erb
<% content_for :page_title do %>
  Banners de categorías
<% end %>

<% if @taxons.any? %>
  <table class="table">
    <thead>
      <tr>
        <th>Categoría</th>
        <th>Banner</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @taxonomies.each do |taxonomy| %>
        <%= category_banner_row(taxonomy.root) %>
        <% if taxonomy.root %>
          <% taxonomy.root.children.each do |taxon_1| %>
            <%= category_banner_row(taxon_1) %>
            <% taxon_1.children.each do |taxon_2| %>
              <%= category_banner_row(taxon_2) %>
              <% taxon_2.children.each do |taxon_3| %>
                <%= category_banner_row(taxon_3) %>
                <% taxon_3.children.each do |taxon_4| %>
                  <%= category_banner_row(taxon__4) %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>      
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info">
    No hay categorías registradas
  </div>
<% end %>

app/views/promotional_banners/categories_add_banner.html.erb
<% content_for :page_title do %>
  <%= "Agregar banner" %>
<% end %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for @promotional_banner, 
                 url: "/promotional_banners/#{@promotional_banner.id}", 
                 multipart: true do |f| %>
      
      <div class="form-group">
        <%= label_tag 'Categoría' %>
        <h5><%= @taxon.name %></h5>
      </div>

      <div class="form-group">
        <%= f.label :image, 'Imagen' %>
        <%= f.file_field :image %>
      </div>  

      <div class="form-group">
        <%= f.hidden_field :taxon_id, value: @taxon.id %>
        <%= f.hidden_field :location, value: :taxon %>
        <%= f.hidden_field :alt, value: "Banner de categoría #{@taxon.name}" %>
        <%= f.submit 'Guardar banner', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/promotional_banners/edit.html.erb
<% content_for :page_title do %>
  Editar Banner
<% end %>

<%= render 'form', url_path: "/promotional_banners/#{@promotional_banner.id}", method_type: :put  %>

app/views/promotional_banners/index.html.erb
<% content_for :page_title do %>
  Banners promocionales
<% end %>

<% if PromotionalBanner.any? %>
  <table class="table">
    <thead>
      <tr>
        <th>Título</th>
        <th>URL Asociada</th>
        <th>Imagen</th>
        <th>Imagen para móviles</th>
        <th>Ubicación</th>
        <th>Estado</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @promotional_banners.each do |banner| %>
        <tr>
          <td><%= banner.title %></td>
          <td><%= link_to banner.link, banner.link.to_s %></td>
          <td><%= image_tag banner.image.url(:thumb) %></td>
          <td><%= image_tag banner.mobile_image.url(:thumb) %></td>
          <td class="banner-localtion"><%= banner.location %>
            <div class="popover-custom" data-toggle="popover" data-html="true" data-placement="left" title="<%= banner.location%>" data-content='<img class="img-responsive" src="<%= banner.location_help_url %>" alt="<%= banner.location %>">'></div>
          </td>
          <th><%= banner.active %></th>
          <th>
            <%= link_to main_app.edit_promotional_banner_path(banner), class: 'btn btn-primary edit-banner' do %>
              <i class="fa fa-pencil"></i> Editar
            <% end %>
          </th>
        </tr>
      <% end %>      
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info">
    No hay banners promocionables
  </div>
<% end %>

<script>
  $(function () {
    $('.popover-custom').popover('show');
    $('.popover-custom').popover('hide');
  });
  $(".banner-localtion").hover(function(){
    $(this).find('.popover-custom').popover('toggle');
  });
</script>

app/views/promotional_banners/new.html.erb
<% content_for :page_title do %>
  Nuevo Banner
<% end %>

<%= render 'form', url_path: '/promotional_banners', method_type: :post  %>