config/routes.rb
  get '/dataUpload/download_stock_template' => 'data_upload#download_stock_template', :as => "stock_template_path"
  get '/dataUpload/download_related_products_template' => 'data_upload#download_related_products_template', :as => "related_products_template_path"
  get '/dataUpload/download_offer_prices_template' => 'data_upload#download_offer_prices_template', :as => "offer_prices_template_path"
  get '/dataUpload/download_products_metadata_template' => 'data_upload#download_products_metadata_template', :as => "products_metadata_template_path"
  get '/dataUpload/download_categories_metadata_template' => 'data_upload#download_categories_metadata_template', :as => "categories_metadata_template_path"

  get '/download/stock' => 'data_upload#download_stock', as: 'download_stock'
  get '/download/products' => 'data_upload#download_products', as: 'download_products'
  get '/download/related_products' => 'data_upload#download_related_products', as: 'download_related_products'
  get '/download/offer_prices' => 'data_upload#download_offer_prices', as: 'download_offer_prices'
  get '/download/products_metadata' => 'data_upload#download_products_metadata', as: 'download_products_metadata'
  get '/download/categories_metadata' => 'data_upload#download_categories_metadata', as: 'download_categories_metadata'

  
  get 'comunas/comuna_by_region' => 'comunas#comuna_by_region'

  post '/lineItem/destroy_item' => 'line_item#destroy_item', :as => "line_item_destroy_item_path"

  get '/tag_manager' => 'tag_manager#index'
  post '/tag_manager/update' => 'tag_manager#update'

  post '/webpay/webpay_final_url', to: 'webpay#webpay_final_url', as: :webpay_result
  post '/webpay/return_url', to: 'webpay#return_url', as: :webpay_return
  post '/webpay/nullify_order', to: 'webpay#nullify_order', as: :nullify_order
  post '/user/update', to: 'local_user#update', as: :update_user
  
  resources :promotional_banners, except: [:destroy, :show]
  get 'promotional_banners/categories', to: 'promotional_banners#categories', as: 'categories_banners'
  get 'promotional_banners/categories/:taxon_id/add', to: 'promotional_banners#categories_add_banner', as: 'add_banner_to_category'

  get 'quotations/new/:product_id', to: 'quotations#new', as: 'quotation_new'
  post 'quotations', to: 'quotations#create', as: 'quotations'
  get 'quotations/success', to: 'quotations#success', as: 'success_quotation_request'

  resources :static_pages
  resources :miele_configs, only: [:index, :edit, :update]

  
  get 'admin/virtual_support', to: 'virtual_support#edit', as: :virtual_support
  patch 'admin/virtual_support', to: 'virtual_support#update'
  get 'agendamiento-cita-virtual', to: 'virtual_support#new', as: :new_virtual_support
  
  Spree::Core::Engine.routes.draw do

    get 'store_notices_controller/index'
    get 'store_notices_controller/new'

    get 'products/:id/list_prices', to: 'products#list_prices', as: 'list_product_prices'

    get 'oportunities', to: 'products#oportunities', as: 'oportunities'

    resources :provinces
    namespace :admin, path: Spree.admin_path do

      resources :reports, only: [:index] do
        collection do
          get :dashboard
          get :sales_total
          get :promotions
          get :promotions_pdf
          get :sales_product_total
          get :sales_product_total_pdf
          post :sales_product_total
          get :viewed_product_total
          get :viewed_product_total_pdf
          get :loyal_customers
          get :loyal_customers_pdf
          get :customers_over_time
          get :customers_over_time_pdf
          get :visits_over_time
          get :visits_over_time_pdf
          get :visits_by_page
          get :visits_by_page_pdf
          post :sales_total
          get :searches
        end
      end
      resources :products, only: [:index] do
        collection do
          post :create_tag
          post :delete_documents
          get :documents
          get :change_state_of_product
        end
      end
      get 'configurations', :to => 'base#configurations', :as => :configurations
      get '/download_users', :to => 'users#download_users', :as => :download_users
      get '/download_new_users', :to => 'users#download_new_users', :as => :download_new_users
      get '/download_orders', :to => 'orders#download_orders', :as => :download_orders
      get '/download_orders_summary', :to => 'orders#download_orders_summary', :as => :download_orders_summary
      delete '/delete_comment/:id', :to => 'comments#destroy', :as => :delete_comment
      get '/new_users', :to => 'users#new_users', :as => :new_users

      get 'orders/:id/ready' => 'orders#ready', :as => :order_ready
      get 'orders/:id/ship' => 'orders#ship', :as => :order_ship
      get 'orders/:id/deliver' => 'orders#deliver', :as => :order_deliver
      get 'orders/update_massive_orders' => 'orders#update_massive_orders', :as => :order_update_massive_orders
      get 'orders/:id/resend_order_to_b2b' => 'orders#resend_order_to_b2b', :as => :resend_order_to_b2b

      get 'products/:id/comparable_attributes', to: 'products#comparable_attributes', as: :product_comparable_attributes
      get 'products/:id/comparable_attributes/:attribute_id/edit', to: 'products#edit_comparable_attribute', as: :edit_product_comparable_attribute
      patch 'products/:id/comparable_attributes/:attribute_id/update', to: 'products#update_comparable_attribute', as: :update_product_comparable_attribute

      get 'products/:id/specific_attributes', to: 'products#specific_attributes', as: :product_specific_attributes
      get 'products/:id/specific_attributes/:attribute_id/:attribute_name/edit/:is_boolean', to: 'products#edit_specific_attribute', as: :edit_product_specific_attribute
      patch 'products/:id/specific_attributes/:attribute_id/update', to: 'products#update_specific_attribute', as: :update_product_specific_attribute

      delete 'orders/:id', to: 'orders#destroy', as: :soft_delete_order

      get '/download_searches' => 'reports#download_searches', as: :download_searches
      get '/download_visits_by_page' => 'reports#download_visits_by_page', as: :download_visits_by_page
      get '/download_visits_over_time' => 'reports#download_visits_over_time', as: :download_visits_over_time
      get '/download_customers_over_time' => 'reports#download_customers_over_time', as: :download_customers_over_time
      get '/download_loyal_customers' => 'reports#download_loyal_customers', as: :download_loyal_customers
      get '/download_viewed_product_total' => 'reports#download_viewed_product_total', as: :download_viewed_product_total
      get '/download_sales_product_total' => 'reports#download_sales_product_total', as: :download_sales_product_total
      get '/download_promotions' => 'reports#download_promotions', as: :download_promotions
      get '/download_sales_total' => 'reports#download_sales_total', as: :download_sales_total
    end
    post 'products/fetch_stock'
    get '/products/most_selled' => 'products#most_selled'
    get 'products/recents' => 'products#recents', :as => :recents 
    get 'webpay/success', :to => 'checkout#webpay_success', :as => :webpay_success
    get 'webpay/error', :to => 'checkout#webpay_error', :as => :webpay_error
    get 'webpay/nullify', :to => 'checkout#webpay_nullify', :as => :webpay_nullify
    post 'store/newsletter' => 'store#newsletter' , :as => 'newsletter_create'
    post 'repeat/repeat_last_complete_order', :to => 'orders#repeat_last_complete_order' , :as => :repeat_last_complete_order
    post 'repeat/repeat_order', :to => 'orders#repeat_order' , :as => :repeat_order
    post 'orders/populate_ajax', :to => 'orders#populate_ajax' , :as => :populate_ajax
    post 'orders/update_ajax', :to => 'orders#update_ajax' , :as => :update_ajax
    post 'products/properties', :to => 'products#properties' , :as => :properties
    post 'orders/custom_apply_coupon', :to => 'orders#custom_apply_coupon' , :as => :custom_apply_coupon
    get 'orders/show_apply_coupon_form', to: 'orders#show_apply_coupon_form', as: :show_apply_coupon_form
    post 'orders/update_step', :to => 'orders#update_step' , :as => :update_step
    patch 'orders/update_item/quantity', to: 'orders#update_item_quantity'
    patch 'orders/update_item/installation', to: 'orders#update_item_installation'
    
    post 'orders/update/shipping_address/ajax', to: 'orders#update_shipping_address_ajax'
    post 'orders/remove_item', to: 'orders#remove_item'
    post 'orders/populate_service', to: 'orders#populate_service'
    get 'products/brands', :to => 'products#brands' , :as => :brands
    get 'taxons/get_taxon', :to => 'taxons#get_taxon' , :as => :get_taxon

    get 'products/rss' => 'products#rss', :as => :rss

    get 'store/privacy_policy', :to => 'store#privacy_policy'
    get 'store/returns_policy', :to => 'store#returns_policy'
    get 'store/maps_and_address', :to => 'store#maps_and_address'
    get 'store/about', :to => 'store#about'
    get 'store/info_delivery', :to => 'store#info_delivery'
    get '/contact', :to => 'store#new_contact', as: :contact
    post '/contact', :to => 'store#send_email_contact'
  end

  namespace :admin do
    resources :reviews, only: [:index, :destroy, :edit, :update] do
      member do
        get :approve
      end
      resources :feedback_reviews, only: [:index, :destroy]
    end
    resource :review_settings, only: [:edit, :update]
  end

  post 'comparator/add_product/:variant_id', to: 'comparator#add_product', as: "comparator_add_product"
  post 'comparator/del_product', to: 'comparator#del_product', as: "comparator_del_product"

  get 'comparator', to: 'comparator#show', as: 'comparator'
  get 'comparator/download', to: 'comparator#download', as: 'comparator_download'

  namespace :api2 do
    namespace :v1, defaults: { format: :json } do
      
      patch 'update_state_order', to: 'miele_api_for_b2b#update_state_order'

app/views/spree/admin/reviews/index.html.erb
<% content_for :page_title do %>
	<%= Spree.t(:reviews) %>
<% end %>
<% content_for :page_actions do %>
  <%= render partial: 'spree/admin/shared/help', locals: {title_help: t(:admin_help_reviews_title), body_help: t(:admin_help_reviews_body)} %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_reviews_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<%= label_tag :q_name_cont, Spree::Review.human_attribute_name(:user) %>
						<%= f.text_field :name_cont, size: 25, class: 'form-control' %>
					</div>
				</div>

				<div class="col-md-6">
					<div class="form-group">
						<%= label_tag :q_title_cont, Spree::Review.human_attribute_name(:title) %>
						<%= f.text_field :title_cont, size: 25, class: 'form-control' %>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<%= label_tag :q_review_cont, Spree::Review.human_attribute_name(:review) %>
						<%= f.text_field :review_cont, size: 25, class: 'form-control' %>
					</div>
				</div>

				<div class="col-md-6">
					<div class="form-group">
						<%= label_tag :q_approved_eq, Spree.t(:approval_status) %>
						<%= f.select :approved_eq, [[Spree.t(:all), nil], [Spree.t(:approved_reviews), true], [Spree.t(:unapproved_reviews), false]], {}, class: 'select2' %>
					</div>
				</div>
			</div>
			<div class="form-actions" data-hook="admin_reviews_index_search_buttons">
				<%= button Spree.t(:filter_results), 'search' %>
			</div>
    <% end %>
  </div>
<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @reviews %>

<% if @reviews.any? %>
	<table class="table" id="listing_reviews">
		<thead>
			<tr>
				<th><%= sort_link @search, :product, Spree.t(:product) %></th>
				<th><%= sort_link @search, :rating, Spree::Review.human_attribute_name(:rating) %></th>
				<th><%= Spree.t(:feedback) %></th>
				<th><%= sort_link @search, :user, Spree::Review.human_attribute_name(:user) %></th>
				<th><%= sort_link @search, :ip_address, Spree::Review.human_attribute_name(:ip_address) %></th>
				<th><%= sort_link @search, :created_at, Spree::Review.human_attribute_name(:created_at) %></th>
				<th data-hook="admin_reviews_index_header_actions" class="actions"></th>
			</tr>
		</thead>
		<tbody>
			<% @reviews.each do |review| %>
				<tr data-hook="admin_reviews_index_rows" id="<%= dom_id review %>" class="<%= cycle('odd', 'even') %>">
					<td><%= link_to_if review.product, review.product.name, product_path(review.product) %></td>
					<td><%= txt_stars(review.rating) %></td>
					<td><%= link_to "(#{review.feedback_stars}/#{review.feedback_reviews.size})", admin_review_feedback_reviews_path(review) %></td>
					<td><%= review.user_id ? link_to(review.user.try(:email), [:admin, review.user]) : Spree.t(:anonymous) %></td>
					<td><%= link_to_if review.ip_address, review.ip_address, "http://whois.domaintools.com/#{review.ip_address}", target: :blank %></td>
					<td><%= l review.created_at, format: :short %></td>
					<td data-hook="admin_reviews_index_row_actions" class="actions">
						<%= link_to_with_icon 'save', Spree.t(:approve), approve_admin_review_url(review), no_text: true, class: 'approve btn btn-default' unless review.approved %>
						<%= link_to_edit review, no_text: true, class: 'edit' %>
						<%= link_to_delete review, no_text: true %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
	<div class="alert alert-info no-objects-found">
		<%= Spree.t(:no_resource_found, resource: Spree.t(:reviews)) %>
	</div>
<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @reviews %>