config/routes.rb
  post '/dataUpload/import_categories' => 'data_upload#import_categories'
  post '/dataUpload/import_products' => 'data_upload#import_products'
  post '/dataUpload/import_images' => 'data_upload#import_images'
  post '/dataUpload/import_stock' => 'data_upload#import_stock'
  get '/dataUpload/uploadBanner' => 'data_upload#uploadBanner'
  post '/dataUpload/upload_banner_image' => 'data_upload#upload_banner_image'
  post '/dataUpload/delete_banner_image' => 'data_upload#delete_banner_image'
  post '/dataUpload/assign_image' => 'data_upload#assign_image'
  post '/dataUpload/import_comparable_attributes' => 'data_upload#import_comparable_attributes', as: 'import_comparable_attributes'
  post '/dataUpload/import_related_products' => 'data_upload#import_related_products'
  post '/dataUpload/import_offer_prices' => 'data_upload#import_offer_prices'
  post '/dataUpload/import_products_metadata' => 'data_upload#import_products_metadata'
  post '/dataUpload/import_categories_metadata' => 'data_upload#import_categories_metadata'
  get'/dataUpload/synchronize_products_with_miele_core' => 'data_upload#synchronize_products_with_miele_core'
  get'/dataUpload/synchronize_stock_and_price_products_with_miele_core' => 'data_upload#synchronize_stock_and_price_products_with_miele_core'

  post '/dataUpload/import_tech_documents' => 'data_upload#import_tech_documents'
  get '/dataUpload/download_categories_template' => 'data_upload#download_categories_template', :as => "categories_template_path"
  get '/dataUpload/download_products_template' => 'data_upload#download_products_template', :as => "products_template_path"
  get '/dataUpload/download_stock_template' => 'data_upload#download_stock_template', :as => "stock_template_path"
  get '/dataUpload/download_related_products_template' => 'data_upload#download_related_products_template', :as => "related_products_template_path"
  get '/dataUpload/download_offer_prices_template' => 'data_upload#download_offer_prices_template', :as => "offer_prices_template_path"
  get '/dataUpload/download_products_metadata_template' => 'data_upload#download_products_metadata_template', :as => "products_metadata_template_path"
  get '/dataUpload/download_categories_metadata_template' => 'data_upload#download_categories_metadata_template', :as => "categories_metadata_template_path"

  get '/download/stock' => 'data_upload#download_stock', as: 'download_stock'
  get '/download/products' => 'data_upload#download_products', as: 'download_products'
  get '/download/related_products' => 'data_upload#download_related_products', as: 'download_related_products'
  get '/download/offer_prices' => 'data_upload#download_offer_prices', as: 'download_offer_prices'
  get '/download/products_metadata' => 'data_upload#download_products_metadata', as: 'download_products_metadata'
  get '/download/categories_metadata' => 'data_upload#download_categories_metadata', as: 'download_categories_metadata'

  
  get 'comunas/comuna_by_region' => 'comunas#comuna_by_region'

  post '/lineItem/destroy_item' => 'line_item#destroy_item', :as => "line_item_destroy_item_path"

  get '/tag_manager' => 'tag_manager#index'
  post '/tag_manager/update' => 'tag_manager#update'

  post '/webpay/webpay_final_url', to: 'webpay#webpay_final_url', as: :webpay_result
  post '/webpay/return_url', to: 'webpay#return_url', as: :webpay_return
  post '/webpay/nullify_order', to: 'webpay#nullify_order', as: :nullify_order
  post '/user/update', to: 'local_user#update', as: :update_user
  
  resources :promotional_banners, except: [:destroy, :show]
  get 'promotional_banners/categories', to: 'promotional_banners#categories', as: 'categories_banners'
  get 'promotional_banners/categories/:taxon_id/add', to: 'promotional_banners#categories_add_banner', as: 'add_banner_to_category'

  get 'quotations/new/:product_id', to: 'quotations#new', as: 'quotation_new'
  post 'quotations', to: 'quotations#create', as: 'quotations'
  get 'quotations/success', to: 'quotations#success', as: 'success_quotation_request'

  resources :static_pages
  resources :miele_configs, only: [:index, :edit, :update]

  
  get 'admin/virtual_support', to: 'virtual_support#edit', as: :virtual_support
  patch 'admin/virtual_support', to: 'virtual_support#update'
  get 'agendamiento-cita-virtual', to: 'virtual_support#new', as: :new_virtual_support
  
  Spree::Core::Engine.routes.draw do

    get 'store_notices_controller/index'
    get 'store_notices_controller/new'

    get 'products/:id/list_prices', to: 'products#list_prices', as: 'list_product_prices'

    get 'oportunities', to: 'products#oportunities', as: 'oportunities'

    resources :provinces
    namespace :admin, path: Spree.admin_path do

      resources :reports, only: [:index] do
        collection do
          get :dashboard
          get :sales_total
          get :promotions
          get :promotions_pdf
          get :sales_product_total
          get :sales_product_total_pdf
          post :sales_product_total
          get :viewed_product_total
          get :viewed_product_total_pdf
          get :loyal_customers
          get :loyal_customers_pdf
          get :customers_over_time
          get :customers_over_time_pdf
          get :visits_over_time
          get :visits_over_time_pdf
          get :visits_by_page
          get :visits_by_page_pdf
          post :sales_total
          get :searches
        end
      end
      resources :products, only: [:index] do
        collection do
          post :create_tag
          post :delete_documents
          get :documents
          get :change_state_of_product
        end
      end
      get 'configurations', :to => 'base#configurations', :as => :configurations
      get '/download_users', :to => 'users#download_users', :as => :download_users
      get '/download_new_users', :to => 'users#download_new_users', :as => :download_new_users
      get '/download_orders', :to => 'orders#download_orders', :as => :download_orders
      get '/download_orders_summary', :to => 'orders#download_orders_summary', :as => :download_orders_summary
      delete '/delete_comment/:id', :to => 'comments#destroy', :as => :delete_comment
      get '/new_users', :to => 'users#new_users', :as => :new_users

      get 'orders/:id/ready' => 'orders#ready', :as => :order_ready
      get 'orders/:id/ship' => 'orders#ship', :as => :order_ship
      get 'orders/:id/deliver' => 'orders#deliver', :as => :order_deliver
      get 'orders/update_massive_orders' => 'orders#update_massive_orders', :as => :order_update_massive_orders
      get 'orders/:id/resend_order_to_b2b' => 'orders#resend_order_to_b2b', :as => :resend_order_to_b2b

      get 'products/:id/comparable_attributes', to: 'products#comparable_attributes', as: :product_comparable_attributes
      get 'products/:id/comparable_attributes/:attribute_id/edit', to: 'products#edit_comparable_attribute', as: :edit_product_comparable_attribute
      patch 'products/:id/comparable_attributes/:attribute_id/update', to: 'products#update_comparable_attribute', as: :update_product_comparable_attribute

      get 'products/:id/specific_attributes', to: 'products#specific_attributes', as: :product_specific_attributes
      get 'products/:id/specific_attributes/:attribute_id/:attribute_name/edit/:is_boolean', to: 'products#edit_specific_attribute', as: :edit_product_specific_attribute
      patch 'products/:id/specific_attributes/:attribute_id/update', to: 'products#update_specific_attribute', as: :update_product_specific_attribute

      delete 'orders/:id', to: 'orders#destroy', as: :soft_delete_order

      get '/download_searches' => 'reports#download_searches', as: :download_searches
      get '/download_visits_by_page' => 'reports#download_visits_by_page', as: :download_visits_by_page
      get '/download_visits_over_time' => 'reports#download_visits_over_time', as: :download_visits_over_time
      get '/download_customers_over_time' => 'reports#download_customers_over_time', as: :download_customers_over_time
      get '/download_loyal_customers' => 'reports#download_loyal_customers', as: :download_loyal_customers
      get '/download_viewed_product_total' => 'reports#download_viewed_product_total', as: :download_viewed_product_total
      get '/download_sales_product_total' => 'reports#download_sales_product_total', as: :download_sales_product_total
      get '/download_promotions' => 'reports#download_promotions', as: :download_promotions
      get '/download_sales_total' => 'reports#download_sales_total', as: :download_sales_total
    end
    post 'products/fetch_stock'
    get '/products/most_selled' => 'products#most_selled'
    get 'products/recents' => 'products#recents', :as => :recents 
    get 'webpay/success', :to => 'checkout#webpay_success', :as => :webpay_success
    get 'webpay/error', :to => 'checkout#webpay_error', :as => :webpay_error
    get 'webpay/nullify', :to => 'checkout#webpay_nullify', :as => :webpay_nullify
    post 'store/newsletter' => 'store#newsletter' , :as => 'newsletter_create'
    post 'repeat/repeat_last_complete_order', :to => 'orders#repeat_last_complete_order' , :as => :repeat_last_complete_order
    post 'repeat/repeat_order', :to => 'orders#repeat_order' , :as => :repeat_order
    post 'orders/populate_ajax', :to => 'orders#populate_ajax' , :as => :populate_ajax
    post 'orders/update_ajax', :to => 'orders#update_ajax' , :as => :update_ajax
    post 'products/properties', :to => 'products#properties' , :as => :properties
    post 'orders/custom_apply_coupon', :to => 'orders#custom_apply_coupon' , :as => :custom_apply_coupon
    get 'orders/show_apply_coupon_form', to: 'orders#show_apply_coupon_form', as: :show_apply_coupon_form
    post 'orders/update_step', :to => 'orders#update_step' , :as => :update_step
    patch 'orders/update_item/quantity', to: 'orders#update_item_quantity'
    patch 'orders/update_item/installation', to: 'orders#update_item_installation'
    

app/helpers/orders_helper.rb
module OrdersHelper

  def order_items_by_courier
    return [@order.mda_and_sda_products, @order.pai_products]
  end

  def tracking_number_by_courier(index)
    if index == 0 and @order.shipments.first.alternative_tracking
      tracking_code = @order.shipments.first.alternative_tracking
      return (link_to tracking_code, 
                      "https://www.starken.cl/seguimiento?codigo=#{tracking_code}",
                      target: '_blank')
    elsif @order.shipments.first.tracking
      return (link_to @order.shipments.first.tracking, "https://alasxpress.com/", target: '_blank')
    end
  end

  def get_courier_name(index)
    if index == 0
      return 'Starken'
    else
      return 'Alas'
    end
  end
end

app/views/spree/admin/orders/_add_line_item.html.erb
<%= render partial: "spree/admin/variants/autocomplete", formats: :js %>

<%= render partial: "spree/admin/variants/autocomplete_line_items_stock", formats: :js %>

<div id="add-line-item" data-hook class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title"><%= Spree.t(:add_product) %></h1>
  </div>
  <div class="panel-body">
    <div data-hook="add_product_name" class="form-group">
      <%= label_tag :add_line_item_variant_id, Spree.t(:name_or_sku) %>
      <%= hidden_field_tag :add_line_item_variant_id, "", class: "variant_autocomplete fullwidth-input" %>
    </div>

    <div id="stock_details"></div>
  </div>
</div>

app/views/spree/admin/orders/_add_product.html.erb
<%= render partial: "spree/admin/variants/autocomplete", formats: :js %>
<%= render partial: "spree/admin/variants/autocomplete_stock", formats: :js %>

<div class="panel panel-default" id="add-line-item" data-hook>
  <div class="panel-heading">
    <h1 class="panel-title">
      <%= Spree.t(:add_product) %>
    </h1>
  </div>
  <div class="panel-body">
    <div data-hook="add_product_name">
      <%= label_tag :add_variant_id, Spree.t(:name_or_sku) %>
      <%= hidden_field_tag :add_variant_id, "", class: "variant_autocomplete fullwidth-input" %>
    </div>

    <div id="stock_details"></div>
  </div>
</div>

app/views/spree/admin/orders/_line_items.html.erb
<% if order.line_items.exists? %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h1 class="panel-title">
        <%= Spree.t(:order_line_item) %>
      </h1>
    </div>
    <table class="table table-bordered line-items" data-hook="line-items">
      <thead>
        <th colspan="2"><%= Spree.t(:name) %></th>
        <th class="text-center"><%= Spree.t(:net_price) %></th>
        <th class="text-center"><%= Spree.t(:iva) %></th>
        <th class="text-center"><%= Spree.t(:quantity) %></th>
        <th class="text-center"><%= Spree.t(:net_total_price) %></th>
        <th class="orders-actions text-center" data-hook="admin_order_form_line_items_header_actions"></th>
      </thead>
      <tbody>
        <% order.line_items.each do |item| %>
          <tr class="line-item" id="line-item-<%= item.id %>">
            <td class="line-item-image image text-center">
              <%= mini_image(item.variant) %>
            </td>
            <td class="line-item-name text-center">
              <%= item.variant.product.name %><br><%= "(" + variant_options(item.variant) + ")" unless item.variant.option_values.empty? %>
            </td>
            <td class="line-item-price text-center"><%= number_to_currency(item.price / 1.19) %></td>
            <td class="line-item-iva text-center"><%= number_to_currency(item.price - (item.price / 1.19)) %></td>
            <td class="line-item-qty-show text-center">
              <%= item.quantity %>
            </td>
            <td class="line-item-qty-edit is-hidden">
              <%= number_field_tag :quantity, item.quantity, min: 0, class: "line_item_quantity form-control", size: 5 %>
            </td>
            <td class="line-item-total text-center"><%= line_item_shipment_price(item, item.quantity) %></td>
            <td class="cart-line-item-delete actions actions-4 text-center" data-hook="cart_line_item_delete">
              <% if can? :update, item %>
                <%= link_to_with_icon 'arrow-left', Spree.t('actions.cancel'), "#", class: 'cancel-line-item btn btn-default btn-sm', data: {action: 'cancel'}, title: Spree.t('actions.cancel'), style: 'display: none', no_text: true %>
                <%= link_to_with_icon 'save', Spree.t('actions.save'), "#", class: 'save-line-item btn btn-success btn-sm', no_text: true, data: { :'line-item-id' => item.id, action: 'save'}, title: Spree.t('actions.save'), style: 'display: none' %>
                <%= link_to_with_icon 'edit', Spree.t('edit'), "#", class: 'edit-line-item btn btn-primary btn-sm', data: {action: 'edit'}, title: Spree.t('edit'), no_text: true %>
                <%= link_to_with_icon 'delete', Spree.t('delete'), "#", class: 'delete-line-item btn btn-danger btn-sm', data: { 'line-item-id' => item.id, action: 'remove'}, title: Spree.t('delete'), no_text: true %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/spree/admin/orders/_order_actions.html.erb
<% content_for :page_actions do %>
  <% if can?(:resend, order) %>
    <%= button_link_to Spree.t(:resend, scope: 'admin.order.events', default: Spree.t(:resend)),
          resend_admin_order_url(order),
          method: :post,
          icon: 'envelope'
    %>
  <% end %>
<% end %>

app/views/spree/admin/orders/_shipment_manifest.html.erb
<% shipment.manifest.each do |item| %>
  <tr class="stock-item" data-item-quantity="<%= item.quantity %>">
    <td class="item-image image text-center">
      <%= mini_image(item.variant) %>
    </td>

    <td class="item-name">
      <%= item.variant.product.name %><br><%= "(" + variant_options(item.variant) + ")" unless item.variant.option_values.empty? %>
      <% if item.variant.sku.present? %>
        <strong><%= Spree.t(:sku) %>:</strong> <%= item.variant.sku %>
      <% end %>
    </td>

    <td class="item-price text-center"><%= number_to_currency(item.line_item.price / 1.19) %></td>
    <td class="item-iva text-center"><%= number_to_currency(item.line_item.price - (item.line_item.price / 1.19)) %></td>

    <td class="item-qty-show text-center">
      <% item.states.each do |state,count| %>
        <%= count %> x <%= Spree.t(state).downcase %>
      <% end %>
    </td>

    <% unless shipment.shipped? %>
      <td class="item-qty-edit is-hidden">
        <%= number_field_tag :quantity, item.quantity, min: 0, class: "line_item_quantity form-control", size: 5 %>
      </td>
    <% end %>
    <td class="item-total text-center">
        <% if item.line_item.instalation %>
            Sí
        <% else %>
            No
        <% end %>
    </td>

    <td class="item-total text-center">
      <%= line_item_shipment_price(item.line_item, item.quantity) %>
    </td>

    <td class="cart-item-delete actions actions-3 text-center" data-hook="cart_item_delete">
      <% if((!shipment.shipped?) && can?(:update, item.line_item)) %>
        <%= link_to_with_icon 'pencil', Spree.t('actions.edit'), "#", class: 'edit-item btn btn-default btn-sm', title: Spree.t('actions.edit'), no_text: true %>
        <%= link_to_with_icon 'cancel', Spree.t('actions.cancel'), "#", class: 'cancel-item  btn btn-primary btn-sm', data: { action: 'cancel' }, title: Spree.t('actions.cancel'), style: 'display: none', no_text: true %>
        <%= link_to_with_icon 'ok', Spree.t('actions.save'), "#", class: 'save-item btn btn-success btn-sm', data: {'shipment-number' => shipment.number, 'variant-id' => item.variant.id, action: 'save'}, title: Spree.t('actions.save'), style: 'display: none', no_text: true %>
        <%= link_to_with_icon 'split', Spree.t('split'), "#", class: 'split-item btn btn-primary btn-sm', data: {action: 'split', 'variant-id' => item.variant.id}, title: Spree.t('split'), no_text: true %>
        <%= link_to_with_icon 'delete', Spree.t('delete'), "#", class: 'delete-item btn btn-danger btn-sm', data: { 'shipment-number' => shipment.number, 'variant-id' => item.variant.id, action: 'remove'}, title: Spree.t('delete'), no_text: true %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/spree/admin/orders/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Order) %> 
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_order), new_admin_order_url, class: "btn-success", icon: 'add', id: 'admin_new_order' %>
  <%= render partial: 'spree/admin/shared/help', locals: {title_help: t(:admin_help_orders_title), body_help: t(:admin_help_orders_body)} %>
<% end if can? :create, Spree::Order %>

<% content_for :table_filter do %>
  <div data-hook="admin_orders_index_search">

    <%= search_form_for [:admin, @search], id: 'search-orders' do |f| %>
      <div class="row">
        <div class="date-range-filter col-md-8">
          <div class="form-group">
            <%= label_tag :q_created_at_gt, Spree.t(:date_range) %>
            <div class="row no-padding-bottom">
              <div class="col-md-6">
                <div class="input-group">
                  <%= f.text_field :created_at_gt, class: 'datepicker datepicker-from form-control', value: params[:q][:created_at_gt], placeholder: Spree.t(:start) %>
                  <span class="input-group-addon">
                    <i class="icon icon-calendar"></i>
                  </span>
                </div>

              </div>
              <div class="col-md-6">
                <div class="input-group">
                  <%= f.text_field :created_at_lt, class: 'datepicker datepicker-to form-control', value: params[:q][:created_at_lt], placeholder: Spree.t(:stop) %>
                  <span class="input-group-addon">
                    <i class="icon icon-calendar"></i>
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_number_cont, Spree.t(:order_number, number: '') %>
            <%= f.text_field :number_cont, class: 'form-control js-quick-search-target' %>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_miele_state, Spree.t(:status) %>
            <select name="q[miele_state]" class="select2">
              <option value="">Todos</option>
              <% @miele_state_selector.each do |s| %>
                <option value="<%= s %>" <%= "selected" if @miele_state_selected == s %>><%= Spree.t("miele_states.#{s}") %></option>
              <% end %>
            </select>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_bill_address_firstname_start, Spree.t(:first_name_begins_with) %>
            <%= f.text_field :bill_address_firstname_start, class: 'form-control' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_bill_address_lastname_start, Spree.t(:last_name_begins_with) %>
            <%= f.text_field :bill_address_lastname_start, class: 'form-control' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_email_cont, Spree.t(:email) %>
            <%= f.text_field :email_cont, class: 'form-control js-filterable' %>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_line_items_variant_sku_eq, Spree.t(:sku) %>
            <%= f.text_field :line_items_variant_sku_eq, class: 'form-control' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_promotions_id_in, Spree.t(:promotion) %>
            <%= f.select :promotions_id_in, Spree::Promotion.applied.pluck(:name, :id), {include_blank: true}, class: 'select2' %>
          </div>
        </div>

        <div class="col-md-4">

          <div class="form-group">

            <div class="checkbox">
              <%= label_tag 'q_completed_at_not_null' do %>
                <%= f.check_box :completed_at_not_null, {checked: @show_only_completed}, '1', '0' %>
                <%= Spree.t(:show_only_complete_orders) %>
              <% end %>
            </div>

            <div class="checkbox">
              <%= label_tag 'q_considered_risky_eq' do %>
                <%= f.check_box :considered_risky_eq, {checked: (params[:q][:considered_risky_eq] == '1')}, '1', '' %>
                <%= Spree.t(:show_only_considered_risky) %>
              <% end %>
            </div>

          </div>

        </div>

      </div>

      <div data-hook="admin_orders_index_search_buttons" class="form-actions">
        <%= button Spree.t(:filter_results), 'search' %>
        <%= link_to spree.admin_orders_path(format: :xlsx, :from_button => 'complete'), class: 'btn btn-info', id: 'download-orders' do %>
          <i class="fa fa-download"></i> Descargar órdenes
        <% end %>
        <%= link_to spree.admin_orders_path(format: :xlsx, :from_button => 'summary'), class: 'btn btn-info', id: 'download-orders-summary' do %>
          <i class="fa fa-download"></i> Descargar Resumen órdenes
        <% end %>
      </div>

    <% end %>

  </div>

<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @orders %>
<%= form_tag url_for(:controller  => "orders", :action => "update_massive_orders"), :method => 'get' do %>
  <div class="multiple-change">
    <div class="btn btn-success multiple-state-change-btn" >Cambio masivo de estado</div>
    <div id="state-change-selector" class="change-selector-container">
      <select name="state" id="state-input-selector" class="select2 change-selector">
        <option></option>
        <option value="ready">Preparar</option>
        <option value="shipped">Enviar</option>
        <option value="delivered">Entregar</option>
      </select>
      <input type="submit" value="Cambiar Estado" class="btn btn-primary">
    </div> 
  </div>

  <% if @orders.any? %>
    <table class="table" id="listing_orders" data-hook>
      <thead>
        <tr data-hook="admin_orders_index_headers">
          <th></th>
          <% if @show_only_completed %>
            <th><%= sort_link @search, :completed_at,   I18n.t(:completed_at, scope: 'activerecord.attributes.spree/order') %></th>
          <% else %>
            <th><%= sort_link @search, :created_at,     I18n.t(:created_at, scope: 'activerecord.attributes.spree/order') %></th>
          <% end %>
          <th><%= sort_link @search, :number,           I18n.t(:number, scope: 'activerecord.attributes.spree/order') %></th>
          <!--<th><%= sort_link @search, :considered_risky, I18n.t(:considered_risky, scope: 'activerecord.attributes.spree/order') %></th>-->
          <th><%= sort_link @search, :state,            I18n.t(:state, scope: 'activerecord.attributes.spree/order') %></th>
          <th>TIPO DOCUMENTO</th>
          <th><%= sort_link @search, :email,            I18n.t(:email, scope: 'activerecord.attributes.spree/order') %></th>
          <th><%= sort_link @search, :total,            I18n.t(:total, scope: 'activerecord.attributes.spree/order') %></th>
          <th>Acción</th>
          <th data-hook="admin_orders_index_header_actions" class="actions"></th>
        </tr>
      </thead>
      <tbody>
      <% @orders.each do |order| %>
        <% case order.miele_state 
          when 'paid'
            next_state = 'ready'
          when 'ready'
            next_state = 'shipped'
          when 'shipped'
            next_state = 'delivered'
          else
            next_state = 'none'
          end
        %>
        <tr data-hook="admin_orders_index_rows" class="state-<%= order.state.downcase %> <%= cycle('odd', 'even') %>">
          <td>
            <input type="checkbox" value="<%= order.id %>" name="orders[<%= "order_id-" + order.id.to_s %>]" class="order-selection" data-next ="<%= next_state %>">
          </td>
          <td>
            <%= @show_only_completed ? l(order.completed_at, format: '%d-%m-%Y %H:%M:%S') : l(order.created_at, format: '%d-%m-%Y %H:%M:%S') %>
          </td>
          <td><%= link_to order.number, edit_admin_order_path(order) %></td>
          <!--<td>
            <span class="label label-<%= order.considered_risky ? 'considered_risky' : 'considered_safe' %>">
              <%= order.considered_risky ? Spree.t("risky") : Spree.t("safe") %>
            </span>
          </td>-->
          <td>
            <% if !order.miele_state.nil?%>
              <span class="label  label-success"><%= Spree.t("miele_states.#{order.miele_state.try(:downcase)}") %></span>
            <%else%>
              <span class="label  label-success"></span>
            <% end %>
          </td>
          <td><%= (order.document_type == 'ticket' ? 'Boleta' : 'Factura') %></td>
          <td>
            <% if order.user %>
              <%= link_to order.email, edit_admin_user_path(order.user) %>
            <% else %>
              <%= mail_to order.email %>
            <% end %>
            <% if order.user || order.email %>
              <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_email_cont" data-ransack-value="<%= order.email %>"></span>
            <% end %>
          </td>
          <td><%= order.display_total.to_html %></td>
          <td>
            <!-- shipments.first.try(:ready?) -->
            <% if can?(:update, order.shipments.first) %>
              <% if order.miele_state == 'paid' %>
                <%= link_to Spree.t(:prepare), admin_order_ready_path(order) , class: 'ship btn btn-warning' %>
              <% elsif order.miele_state == 'ready' %>
                <%= link_to Spree.t(:ship), admin_order_ship_path(order), class: 'ship btn btn-primary' %>
              <% elsif order.miele_state == 'shipped' %>
                <%= link_to Spree.t(:delivery),admin_order_deliver_path(order), class: 'ship btn btn-success' %>
              <% elsif order.miele_state == 'delivered' %>
                <button class="ship btn btn-success" disabled>Entregar</button>
              <% end %>
            <% end %>
          </td>
          <td class='actions actions-2' data-hook="admin_orders_index_row_actions">
            <%= link_to_edit_url edit_admin_order_path(order), title: "admin_edit_#{dom_id(order)}", no_text: true %>
            <%= link_to_delete order, :no_text => true, :url => admin_soft_delete_order_url(order.id) %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="alert alert-info no-objects-found">
      <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Order)) %>,
      <%= link_to(Spree.t(:add_one), new_admin_order_url) if can? :create, Spree::Order %>!
    </div>
  <% end %>
<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @orders, simple: true %>

<script>
  $(document).ready(function(){
    $(".js-show-index-filters").click();
    $("#state-change-selector").hide();
    $(".order-selection").hide();
  });

  $(".multiple-state-change-btn").click(function() {
    $("#state-change-selector").show();
    $(".loader-page").remove();
  });

  $("#state-input-selector").change(function(e) {
    $(".order-selection").hide();
    const valueSelector = e.target.value
    $(".order-selection").each(function() {
      if (valueSelector == $(this).data("next")) $(this).show();
    });
  });
</script>